### ISSUE TITLE
Support slonik@33.1.0

### ISSUE THREAD

**Issue by elnygren** [gajus/slonik-utilities#20]
```
npm ERR! peer slonik@"^28 | ^29" from slonik-utilities@2.0.1
```

**Comment by thomaspeklak** [comment]
I just ran into this issue on a fresh `npm install slonik-utilities`. @gajus  Any updates here? It seems that 2.0.1 should work fine with 33, https://github.com/gajus/slonik-utilities/commit/7c3239ea16929285214849bda296bf00b43a314e?w=1

So an update to the peerDependencies should be possible, correct?
