### ISSUE TITLE
slonik-utilities date time compatibility

### ISSUE THREAD

**Issue by TriStarGod** [gajus/slonik-utilities#8]
Hi,
I made my own utilities using slonik but found dates not handled by default. Research led me to https://github.com/gajus/slonik/issues/113 .

I read this utilities code but it doesn't seem to check for date types. Does this utility automatically handle dates?

**Comment by gajus** [comment]
I don't understand what the question is, what feature you are asking about?

**Comment by TriStarGod** [comment]
According to the open issue https://github.com/gajus/slonik/issues/113 , date object types aren't handled automatically by slonik. Dates have to be converted to milliseconds ( `to_timestamp(${date.getTime()} / 1000)` ). I discovered this error while trying to migrate a project from knex to slonik.

Before I went and built a custom function to handle my situation, I checked the slonik-utilities on how it dealt with this situation. As far as I can tell, it doesn't. I just wanted to confirm this is true.

**Comment by gajus** [comment]
What is an example of where it is "unhandled" by `slonik-utilities`?

**Comment by raine** [comment]
In my case, trying to use `update()`  with a `namedAssignmentPayload` parameter that may include `Date`s as values.

Struggling to find a nice solution, but came up with this: 

```ts
function mapDatesToStrings(
  obj: Record<string, Date | boolean | number | string | null>
): Record<string, boolean | number | string | null> {
  return _.mapValues(obj, (v) => (v instanceof Date ? v.toISOString() : v));
}

update(
  connection,
  'table',
  mapDatesToStrings(obj),
  mapDatesToStrings(where)
);
```

Does it sound reasonable that slonik-utilities could be Date aware in that regard?
